#!/usr/bin/env node
// dsh-lifecycle — 声明式项目生命周期协调器（核心逻辑，CLI 版）
// 用法：
//   lifecycle init <name> [--type dsh-plugin] [--dir <path>] [--skills a,b] [--no-git] [--lock <ver>]
//   lifecycle sync          # 在项目目录内运行：读声明 → 对比模板 → 重渲染 .dsh/generated/
//   lifecycle adopt [--type X]  # 老项目：探测/指定 type，生成声明 + 首次 sync
//   lifecycle ls            # 列出可用类型
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SKILLS_ROOT = process.env.DSH_SKILLS ?? 'D:\\tools\\skills';
const root = dirname(fileURLToPath(import.meta.url));
const typesDir = join(root, '..', 'types');
const cmd = process.argv[2];

function loadYaml(text) {
  // 极简 YAML 解析：顶层键 + | 块 + "- item" 列表
  const out = {};
  const lines = text.split('\n');
  let key = null, block = [];
  const flush = () => {
    if (!key) return;
    const v = block.join('\n').replace(/^\n|\n$/g, '');
    if (v) {
      if (/^- /m.test(v)) {
        out[key] = v.split('\n').map(l => l.replace(/^- /, '').trim()).filter(Boolean);
      } else {
        out[key] = v;
      }
    }
    block = [];
  };
  for (const line of lines) {
    if (/^[\w-]+:/.test(line) && !line.startsWith('  ')) {
      flush();
      const m = line.match(/^([\w-]+):\s*(.*)$/);
      key = m[1];
      const v = m[2].trim();
      if (v === '|') { /* block follows */ }
      else if (v) out[key] = v.replace(/^["']|["']$/g, '');
      else out[key] = '';
    } else if (key && (line.startsWith('  ') || line.trim() === '')) {
      block.push(line.replace(/^  /, ''));
    }
  }
  flush();
  return out;
}

function loadType(name) {
  const p = join(typesDir, name + '.yaml');
  if (!existsSync(p)) throw new Error('未知类型: ' + name + '（可用: ' + listTypes().join(', ') + '）');
  const t = loadYaml(readFileSync(p, 'utf8'));
  if (t.extends) {
    const parent = loadType(t.extends);
    return { ...parent, ...t, skills: { ...parent.skills, ...t.skills } };
  }
  return t;
}

function listTypes() {
  return readdirSync(typesDir).filter(f => f.endsWith('.yaml')).map(f => f.replace('.yaml', ''));
}

function renderGenerated(type, project, lockVer) {
  const rules = type.rules_md || '';
  let declared = project.skills;
  if (typeof declared === 'string') declared = declared.trim() ? [declared] : [];
  const skills = (Array.isArray(declared) && declared.length ? declared : (type.skills?.default ?? []));
  const rulesDoc = `<!-- GENERATED BY dsh-lifecycle (type:${type.name} v${type.version}, rules:${project.rules}) — 勿手改 -->\n\n${rules}`;
  const lock = {
    schema: 1,
    type: project.type,
    rules: project.rules,
    templateVersion: type.version,
    skills,
    updatedAt: new Date().toISOString(),
  };
  return { rulesDoc, lock };
}

function syncProject(projDir, { lockVer } = {}) {
  const declPath = join(projDir, 'dsh.project.yml');
  if (!existsSync(declPath)) {
    console.error('未找到 dsh.project.yml（先 lifecycle init 或 adopt）');
    process.exit(1);
  }
  const project = loadYaml(readFileSync(declPath, 'utf8'));
  const type = loadType(project.type);
  const { rulesDoc, lock } = renderGenerated(type, project, lockVer);
  const gen = join(projDir, '.dsh', 'generated');
  mkdirSync(gen, { recursive: true });
  writeFileSync(join(gen, 'rules.md'), rulesDoc, 'utf8');
  writeFileSync(join(gen, 'skills.lock'), JSON.stringify(lock, null, 2) + '\n', 'utf8');
  console.log('==> .dsh/generated/ 已更新 (type=' + project.type + ' v' + type.version + ', rules=' + project.rules + ')');
  return { project, type };
}

// ---- 命令分发 ----
if (cmd === 'ls') {
  console.log(listTypes().join('\n'));
  process.exit(0);
}

if (cmd === 'init') {
  const name = process.argv[3];
  if (!name) { console.error('用法: lifecycle init <name> [--type dsh-plugin] [--dir <path>] [--skills a,b] [--no-git] [--lock <ver>]'); process.exit(1); }
  const flag = (f) => process.argv.includes(f);
  const opt = (f) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : null; };
  const typeName = opt('--type') ?? 'dsh-plugin';
  const dir = opt('--dir') ?? process.cwd();
  const skillsArg = opt('--skills');
  const lockVer = opt('--lock') ?? 'latest';
  const proj = join(dir, name);
  if (existsSync(proj)) { console.error('项目已存在: ' + proj); process.exit(1); }
  mkdirSync(proj, { recursive: true });
  mkdirSync(join(proj, '.dsh'), { recursive: true });

  const type = loadType(typeName);
  const skills = skillsArg ? skillsArg.split(',').map(s => s.trim()) : (type.skills?.default ?? []);
  const decl = `schema: 1\ntype: ${typeName}\nrules: ${lockVer}\n${skills.length ? 'skills:\n' + skills.map(s => '  - ' + s).join('\n') + '\n' : ''}lifecycle: growing\n`;
  writeFileSync(join(proj, 'dsh.project.yml'), decl, 'utf8');
  // AGENTS.md 稳定指针
  writeFileSync(join(proj, 'AGENTS.md'), type.agents_md + '\n', 'utf8');
  // 首次 sync
  syncProject(proj);
  // git init
  if (!flag('--no-git')) {
    try {
      execFileSync('git', ['init'], { cwd: proj, encoding: 'utf8', stdio: 'ignore' });
      execFileSync('git', ['add', '-A'], { cwd: proj, encoding: 'utf8', stdio: 'ignore' });
      execFileSync('git', ['commit', '-m', 'chore: init ' + name + ' (dsh-lifecycle type=' + typeName + ')'], { cwd: proj, encoding: 'utf8', stdio: 'ignore' });
      console.log('==> git 已初始化并提交');
    } catch (e) { console.warn('(!) git init 跳过: ' + String(e).slice(0, 60)); }
  }
  console.log('\n✅ ' + proj);
  process.exit(0);
}

if (cmd === 'sync') {
  syncProject(process.cwd());
  process.exit(0);
}

if (cmd === 'adopt') {
  const opt = (f) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : null; };
  const typeName = opt('--type');
  const cwd = process.cwd();
  // 探测：package.json + cordis.patch.yml → dsh-plugin；否则 base
  const guessed = (existsSync(join(cwd, 'cordis.patch.yml')) || existsSync(join(cwd, 'package.json'))) ? 'dsh-plugin' : 'base';
  const t = typeName ?? guessed;
  console.log('==> adopt: 探测类型 = ' + t + (typeName ? '' : '（可 --type 覆盖）'));
  if (!existsSync(join(cwd, 'dsh.project.yml'))) {
    const type = loadType(t);
    const defSkills = type.skills?.default ?? [];
    const decl = `schema: 1\ntype: ${t}\nrules: latest\nskills:\n${defSkills.length ? defSkills.map(s => '  - ' + s).join('\n') : ''}\nlifecycle: growing\n`;
    writeFileSync(join(cwd, 'dsh.project.yml'), decl, 'utf8');
    writeFileSync(join(cwd, 'AGENTS.md'), type.agents_md + '\n', 'utf8');
  }
  syncProject(cwd);
  console.log('✅ adopt 完成。之后由 dsh-lifecycle 自动维护 .dsh/generated/');
  process.exit(0);
}

console.log('未知命令: ' + cmd + '（可用: init / sync / adopt / ls）');
